language: node_js
node_js:
- '6'
install:
- npm install
- node build.js
deploy:
- provider: s3
  access_key_id: AKIAJOAF2MOLL26BXJPA
  secret_access_key:
    secure: BG8lb3CPpnUoiZTNOALDiYS+RItyADl0XWIrgpqyrlULvtOE14ZkYcgpgR5xzyTwJEDZGH47/Or21tR4kGPAYdITjEkkxmFNE/jxh49pr9pV0KAB8srQSpNaJLwVAdqI3ydHbTBEG6m8wGSktH3PI3YYdJga1Ki/G4e0jeCauvyTNXY6dcLQQky9j1a2Gto/ZP+GPrwhFPMEZAnNPiNLOJEQUoUvw9aYOVRvt4BaUIanp4tt3nwre+FDsOFrGY6KYVTo0RJPdDndNj+Nwh8R0FDdBfeS6GzLWm/U/DOVnvP/ysY0sUN4j1cS6kQDZVwVI0FbhLjAXYKlycu4Bs4VETyuYe/rKfKwqA3HdBZHQPRBpnn418j+9ATrlnwLPqahIcFxJzEBDJsZXNNmTJM0MmFbcoS9T5gzO5fCOJExpguCjTK3HCfgP1KoOUu3uScZ0om0F3EWWdPveNkgnZxFYSrQWyNLh9AMVDs9H+LKQCHCO1un+sAA7vOdw4KT9Bo7NKPS5njD5zCwxkCEj8T0pp9j19dBxMGefaQwGGLbefnRdw53NraNAJ78AziFUyyfcJQfyUOOf0fUH2dyo2coZxGNvZHNO0/ZQN3LpHH7FER+Hqy6xPVNgV2X5FK84qUjrcr3w40uYcEuutExd7pO2OVJ/ucPBm2fYQxRg2+Kf4Y=
  skip_cleanup: true
  local_dir: build
  bucket: gochefit.scoble.tech
  region: us-east-1
  on:
    branch: master
- provider: s3
  access_key_id: ''
  skip_cleanup: true
  local_dir: build
  bucket: gochefit.com
  region: us-east-1
  on:
    branch: prod
env:
  secure: XwPohL9ruDsIt8hUBc7a36yRoIRmwu5JarUf6sYgDDlitfPhbyR306f4eiYyNlhorhzAxIJCsyDTSxU/0OcbLbZ8vPN6DVOI/507jeIMk3+5nGBnn+WTbYehAgNPm15PLYDVmOoUuzJdOHh1Swfu+BCRgJ6glDKAmfWr6hyF0xxiFR9w91ei5GObN1ROSQta9Z2+4ScZrjhBh3HDI4INJDx+4CyrYy/19zNukXIIwJJsxM8JS2C2pZ0gWuHD0WoR7AWce4QuPzTJj7z7JG7khZfB7Qq+is6e+rOEbYmh7ijngVYK9Fh9e/vQnvSxz2XOMukMndRDM8QnSz4oYdbMLc3wzdc50MKH5niHod1llHxkOK61TUAoxmQYX0oqgqNXSKq+joc18L0J+18fYZJ94pmtSbIJrgLENTevFkZ55PeZ6hu8FC+YiUw5ZhZfjLIG9C1q9WU7yeZW7RO2/tn47vBBTJmObdD5m6ZO/7Dk1j63PDvI9OvKTHKJBAb7kbzFEJt7sXK/od5cnSlNueBD6W5SC1rlktAG2YpoOEkT9iuD7nrF0f95KTIvTR1ovwJs3qkFufJzxwk213vp06jlTW5lWTI0jBpsCVlB6M0N/XLwQ/+msO+nv92JeHyDPx3LvmObdUE5KMQGM30of89hMYQDVag5vQ/Mkbe8rAig+9s=
notifications:
  slack:
    on_success: always
    on_failure: change
    template:
    - "%{build_url}"
    - "%{commit_message}"
    - 'Change view: %{compare_url}'
    rooms:
      secure: YK15DMSwKBTO/awEHJ6ljWkRJvXWreJa5++52cqHk0eIii7/jJLgJ5BTPGn+Ied43qzQTq/xkbywcVmwNBuPDUtbJCh6q9c8SjDJeD+2szvZZRhN0Nx/nKUHXP7YfKYAYVyEWx7YcpcKao+FhpKpU7Lg3YWweysJmy3knUcetakWflCTLWTir0wKvsLVBwd1tBSbbMDDk1COK1KQtGqZzo55J9B7arvHp0NmWDb5TAR4br03vswizPxY1tylpXvUrIcQwU1aRlpdOQgzustLKKRRetBStd5rkqHvPoYiFb7ukokqB5uiFy7uLlYDvg/zUhOTOWj0r/sVvK/1gjYOQWY9owuCV5Et32ESuN1lMkrAYFgBQALEcjxO5rdt0AlrBlgpSoK2R9gFPaqsDyonpwqLFmpD645+ZNh2kUb4C22KgyCJsbXKnlDzdtRi7yddyl3piCU8k6MwLF2ayvvqKELAKli7LXxZgye58UYXoKU2DcbFVIu5WajwPGf2cbZieaTjtJEfcpUGBez8ZB1LuDKB7AMcOfIYRjXgzcv41dad1773VqV6qtPhZQXBKpWy3KMHtuaot6pOkTYpSi0NUZRZVuw+uKvm8i4bqrJD1vb6kg8SQ5lOPOYdMKgZIUjwEGYkXcLVDhuhOQ+hewfeubu8oG0cckaGe/6LOY7Ut3Y=
