language: node_js
node_js:
  - "6"
install:
  - npm install
scripts:
  - node build.js
deploy:
  - provider: s3
    access_key_id: ""
    secret_access_key: ""
    skip_cleanup: true
    local_dir: build
    bucket: gochefit.scoble.tech
    region: us-east-1
    on:
      branch: master
  - provider: s3
    access_key_id: ""
    secret_access_key: ""
    skip_cleanup: true
    local_dir: build
    bucket: gochefit.com
    region: us-east-1
    on:
      branch: prod
env:
  - secure: "syFso2IT/mzAen0iFBvAcBunmdqsBKrHk/g3xxaiwNE4+ftDduJZmiW2np0TpokJYNcnPDj24MMMAUNyFn+F7ZsovpHhmOI/wuIxmulrvpIxSD0EEm84d7/BT3/ifZwao2FcOclUPTnVCd6IEtjF3t0nkVGcZ6fXmQUfc3iD9R1vN4uY6Gii3HAp3p1YUjPgy2EHaQBN/NDKD5y+c4aS+bXp9UvqpF8EbuM0QdKo4XvoT9/jJiUb2GyhLqbaKQX8h24THLxm7odsU8u0VViVwweZWNrC56UO8/i9MNJz+Xe+P3BRrQ5Cn3H27Fv4Xtbh2YM2T4KLq+1IIPnKMP7+T1asaldtdUIC/S36rUFRQskUnFigDyc2bF5qfCu396+QLxZbEz7zv82zWxbt7/RqVZiJHXHNLPdUbnPz/4uaWiV+UZJc0ctBNccwLvx4Rzhv3mpxqNlpRwXf+IP5g2MZOtTVxoUIV/1Gz/sKMbLb4k4bHuoo2xjDefDi22sqU3JYKNWMDArZU7XiCBk5rJS1So9rz+jvSEjimhh9YYC5ke6Z0qWdFuIzfLw3IHuAQLvDctVr+Elf6jJ+Q5aXa/9Iv2wxY/AJejgnUXO/kuG16C/XPzt1FQIlLZLCimE8dOs5mImeAMCiQCye15uNlORerYL0i4C7Qjd6UFi0kSXtHZU="
  - secure: "XcrFSvHM3SX/Zzn88W3zKIaXsKWpTCQlqvOCXp7n1B5hYqp1izfn1Atdc3ujRoODUmUvPIHN0XdDY01otyo9pAwPKc+ax+SdbeH8PcH41fHVUY1jZoNG9ehohODXMSLPes6wv+tN6YAJoFjBygwJYPnnoZMSbL476oNIjIAnnGX8HzcvJmZbMLaxWpGXMWNEZpySeB1Ee7Kf7RRZiDeiG0zrjQBKvAtzKvxIDhbXEBeLck+t5vtzS1wLvdFQivHaCjhxfkcOhqStBzlg3rlhflxmyB5PmXG8GAxf22hmmqJF5OXNicb8oN+BJ5WCt+t9dT2AJ0hvRSZGQDhUSHk93Yqo3FuX6ggQtwJtFCAwDUNqurtXJBt4mEOOALzlI0sXHzgf02ccM2op1TXox4bEDL7srRFL3V0uwaFTyePVudnd3y6B0vw1aWenUaOHNAneu6rBIwuy6JUVjYjCa/VdaGJNxQi6G8N6BNZDuqqq2WWtfHv9PaZ/M/JGunwWYfEi4XPLVyjJxGoYg/pszWUXZvI6W6i3NIsu53JzzMo+2pOVgdQAPIT1XZLcVt+m86CKMdqx7R1kfrylZQcBpw/ewh1EIm4RDmu+V4By7XhlYZa+xRKFz+7TdHUEiZRwtzUX1FnPK0SFA5IkZ3dRnmeGNN+yM6mZHPfQ/B+REHErvBc="
  - secure: "Qf785g37EtMh7iYKzOpa+nM/6ixNHHA3hBp1MRlPMKxEU+Yn7SuDGpuqmkf5FFx3xO+CBo51TgcmOD4LsYgTMoy8+XWRtfUnrw7RA/+XenjNPZ9E/hi5r8b3B8KcmaoZcXq1A/R2C4dwLvwSp2CJsVNVP4M2UJWYt+lDxXEKcpHKTDSeic6jFvCWeCqFM4GPV98Up3w3D0ZiweJzRwy63FVFgeHsM0pHLehpfk8CR1QP2+1LtYmWgP2ruPeT0UEdw2nxzCa6LHQUb6ros2Asph1N/sRqdc8xkbFoQEOm6x+6kMF+alRD4X37KA2jKUcnVeCGBhx8Us69h950voeCSy3mFmTcKcIqtxwgBQKNw5k6mPwm+d3en7Dj/GMb9R+quqxG8YUHOj293/EaahIr38oP3ewnwMxKH0vShj0cFavUtqUaemxVjBcpRMcWZiwblKlrBifqI+ln1imdLWoObAT/sbIOIboDG+4nAJk25N/Mk3uOv2x29+l7RVKABqq5JWhDWHvYI50xuVjWwu3kSctP5S7W7zZPJRR6WcdfJNbFzrBRzQmJNPg5wcTSM7P9Yy74TeRNcuGNZVz8qrDRdfKlyx2xqqQ3BelhhG18oQ6UkhszQQlAGVTOVogNSM0VGOy3vEvUGvuxVVeqQCu2rpomV2TMgC3Xk+++hwza73I="
