language: node_js
node_js:
- '6'
install:
- npm install
- node build.js
deploy:
- provider: s3
  access_key_id: AKIAJOAF2MOLL26BXJPA
  secret_access_key:
    secure: BG8lb3CPpnUoiZTNOALDiYS+RItyADl0XWIrgpqyrlULvtOE14ZkYcgpgR5xzyTwJEDZGH47/Or21tR4kGPAYdITjEkkxmFNE/jxh49pr9pV0KAB8srQSpNaJLwVAdqI3ydHbTBEG6m8wGSktH3PI3YYdJga1Ki/G4e0jeCauvyTNXY6dcLQQky9j1a2Gto/ZP+GPrwhFPMEZAnNPiNLOJEQUoUvw9aYOVRvt4BaUIanp4tt3nwre+FDsOFrGY6KYVTo0RJPdDndNj+Nwh8R0FDdBfeS6GzLWm/U/DOVnvP/ysY0sUN4j1cS6kQDZVwVI0FbhLjAXYKlycu4Bs4VETyuYe/rKfKwqA3HdBZHQPRBpnn418j+9ATrlnwLPqahIcFxJzEBDJsZXNNmTJM0MmFbcoS9T5gzO5fCOJExpguCjTK3HCfgP1KoOUu3uScZ0om0F3EWWdPveNkgnZxFYSrQWyNLh9AMVDs9H+LKQCHCO1un+sAA7vOdw4KT9Bo7NKPS5njD5zCwxkCEj8T0pp9j19dBxMGefaQwGGLbefnRdw53NraNAJ78AziFUyyfcJQfyUOOf0fUH2dyo2coZxGNvZHNO0/ZQN3LpHH7FER+Hqy6xPVNgV2X5FK84qUjrcr3w40uYcEuutExd7pO2OVJ/ucPBm2fYQxRg2+Kf4Y=
  skip_cleanup: true
  local_dir: build
  bucket: gochefit.scoble.tech
  region: us-east-1
  on:
    branch: master
- provider: s3
  access_key_id: ''
  skip_cleanup: true
  local_dir: build
  bucket: gochefit.com
  region: us-east-1
  on:
    branch: prod
notifications:
  slack:
    on_success: always
    on_failure: always
    template:
    - https://github.com/%{repository_slug}
    - "%{build_url}"
    - "%{commit_message}"
    - 'Change view: %{compare_url}'
    rooms:
      secure: YK15DMSwKBTO/awEHJ6ljWkRJvXWreJa5++52cqHk0eIii7/jJLgJ5BTPGn+Ied43qzQTq/xkbywcVmwNBuPDUtbJCh6q9c8SjDJeD+2szvZZRhN0Nx/nKUHXP7YfKYAYVyEWx7YcpcKao+FhpKpU7Lg3YWweysJmy3knUcetakWflCTLWTir0wKvsLVBwd1tBSbbMDDk1COK1KQtGqZzo55J9B7arvHp0NmWDb5TAR4br03vswizPxY1tylpXvUrIcQwU1aRlpdOQgzustLKKRRetBStd5rkqHvPoYiFb7ukokqB5uiFy7uLlYDvg/zUhOTOWj0r/sVvK/1gjYOQWY9owuCV5Et32ESuN1lMkrAYFgBQALEcjxO5rdt0AlrBlgpSoK2R9gFPaqsDyonpwqLFmpD645+ZNh2kUb4C22KgyCJsbXKnlDzdtRi7yddyl3piCU8k6MwLF2ayvvqKELAKli7LXxZgye58UYXoKU2DcbFVIu5WajwPGf2cbZieaTjtJEfcpUGBez8ZB1LuDKB7AMcOfIYRjXgzcv41dad1773VqV6qtPhZQXBKpWy3KMHtuaot6pOkTYpSi0NUZRZVuw+uKvm8i4bqrJD1vb6kg8SQ5lOPOYdMKgZIUjwEGYkXcLVDhuhOQ+hewfeubu8oG0cckaGe/6LOY7Ut3Y=
env:
  secure: pYGuVCYA4MFl4u3B/tQAPmEkA9ovDEFZuOV57HwKlUaK9fmZvDA4zr1uh/L6IZM+g0nC5aYj1vwLz42FxiLxQ5eoYq2d5CEpX1sYDAb7l4rn7ZawFByBXmiAoekxsM0L+nsSn6tckY2FQC+lw+vzkWS5eX0qP2mMNwEe0hYMyKOHj6aNMJ6ezyfd3yX27esYAOq3nJwNsPzzVV0yBtk9saZQ/FsMMO2vUChoIqhh/v4+NoiTYYYzcfV2wWPr4iEYzjZHFk2cKCyiMng2SXTz2psEbGU03CPHi4wJNZHmks8KSBrz3no3NVMwqCKUB9ymmjX22kt3JG0DluVP3Cwqbs378lexIlY4nSKfk/l1Ux3zmcFxdFR2BBjRCazL555kE1sGnC+r4swuPCweKnr0GztGdvJOm47HydZXzWeuCOrfN0gp+nZH+6OEWcFZyOBj9G/+s4zBmi+CW/zzuSBUa/po+V0iDyQjNT7ABGhNA2/eezai1agKXpvVF2MR6pbpvhzT5ee/5hEHeHSOmw0WVb4qzUiH01t8oQFVISDYBi/ApCAMyCea475JDkx+uMIUzfWFrdZuSGN4jUzxCb/WpzuWluv5VmGLFq7gvFyihJhYnv3D7PL2tMwdE6FM3LcVmHh6qP2OvS39Nxfv/agJE7L7yRdQIrMoabn2hhh66LA=
